@startuml
'https://plantuml.com/class-diagram

class MainActivity {
-Button mButtonDanger
-Button mButtonDatabase
-Button mButtonMap

}

class Danger {
 -webView: WebView
}

class MyWebViewClient {
 +shouldOverrideUrlLoading()
}

class DataBase {
+ updateCurrentPosition(Intent):void
+ onCreateContextMenu(ContextMenu, View, ContextMenu.ContextMenuInfo):void
+ onContextItemSelected(MenuItem):boolean
+ deleteForId(long id):void
# onActivityResult(int requestCode,int resultCode, Intent):void
- addCurrentPosition():void
- deleteAll():void
- displayCurrent():void
}

class Observe {
- {static} ContentResolver mContentResolver
- Messenger mReqMessengerRef
-  Messenger mReplyMessenger
- ServiceConnection mSvcConn
+ onServiceConnected(ComponentName,IBinder):void
+ onServiceDisconnected(ComponentName):void
- calculateDistanceAndDisplay(double, double):void
- startPositionBindService():void
}

class ReplyHandler {
- Observe observe
+ handleMessage(Message):void
}

class PositionBindService {
- PositionRequestHandler mPositionRequestHandler
- Messenger mReqMessenger
+ onBind(Intent):IBinder
+ onCreate():void
}

class PositionRequestHandler {
~ Message reply
- double lat, lon
+ handleMessage(Message):void
}

class Position {
- {static} String ACTION_POSITION_RECEIVER
- double geoLan, geoLong
- String goMap
- registerPositionReceiver():void
- displayCurrentGoogleMap(String):void
- displayLatLong(double, double):void
}

class PositionReceiver {
+  onReceive(Context, Intent):void
}

class CurrentLocation {
- {static} String ACTION_POSITION_RECEIVER
+ currentPosition():void
}

class DataBaseHelper {
- String SQL_CREATE_TABLE
+ onCreate(SQLiteDatabase):void
+ onUpgrade(SQLiteDatabase, int, int):void
}

class DangerProvider {
- mDataBaseHelper
+ insert(Uri, ContentValues):Uri
+ delete(Uri, String, String[]):int
+ query(Ui, String[], String, String[], String):Cursor
+ update(Uri, ContentValues, String, String[]):int
}

class DBContract {
+ {static} String CONTENT_AUTHORITY
+ {static} Uri BASE_CONTENT_URI
+ {static} String PATH_CHARACTER
}

abstract class FeedEntry {
+ {static} Uri CONTENT_URI
+ {static} String TABLE_NAME
+ {static} String COLUMN_DANGER
+ {static} String COLUMN_LATITUDE
+ {static} String COLUMN_LONGITUDE
+ {static} String COLUMN_DESCRIPTION
}

MainActivity --> Danger
MainActivity --> Observe
MainActivity --> DataBase
DataBase <--> Position
DataBase --> DangerProvider
DBContract +-- FeedEntry
Position +-- PositionReceiver
Observe +-- ReplyHandler
Observe --> PositionBindService
PositionBindService --> PositionRequestHandler
PositionRequestHandler "mReqMessengerRef" <--> "Message reply" ReplyHandler
DangerProvider --> DataBaseHelper
Danger +-- MyWebViewClient
Position --> CurrentLocation
CurrentLocation --> PositionReceiver

@enduml